services:
  - type: web
    name: house16plus
    runtime: ruby
    plan: free
    buildCommand: './bin/render-build.sh'
    startCommand: './bin/rails server'
    envVars:
      - key: postgresql://house16plus:TjQk9MW73rEno2AvOgueVCFdsfDAepQN@dpg-d1egfk2li9vc73a1jfdg-a/house16plus
        fromDatabase:
          name: house16plus
          property: connectionString
      - key: 981dde69e4eab7aebb0a4acce99c3e18
        sync: false
      - key: WEB_CONCURRENCY
        value: 2
databases:
  - name: house16plus
    plan: free